# Generated by Django 2.0.2 on 2018-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackdata',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='trackdata',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trackdata',
            old_name='date_modified',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='trackdata',
            name='resume_words',
        ),
        migrations.RemoveField(
            model_name='trackdata',
            name='username',
        ),
        migrations.AlterField(
            model_name='trackdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
